collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.8835126
  lightness: 0.7437276
  brandColors:
    - '#FFFFFF'
    - '#CEE07A'
    - '#BCD741'
    - '#DFEAAA'
    - '#EEF4D0'
  rhythmicContrast: 0.7634408
typography_spectrum: 0.374552
layout_spectrum: 0.2455197
name: EliteLevelFitness
